app:
    debug: false

database:
    hostname: localhost
    username: ors
    password: rilinc
    database: research

site:
    annualreports_url: http://annualreports.mtroyal.ca
    researchweb_url: http://research.mtroyal.ca
    template_debug: false 
